package com.civicsense.complaint.entity;

public enum ComplaintDepartment {

    ROADS_AND_TRAFFIC,
    STORM_WATER_DRAINAGE,
    SEWERAGE,
    WATER_SUPPLY,
    SOLID_WASTE_MANAGEMENT,
    STREET_LIGHTING,
    PUBLIC_HEALTH,
    HORTICULTURE_AND_PARKS,
    BUILDING_AND_MAINTENANCE,
    TOWN_PLANNING,
    ENCROACHMENT,
    ENVIRONMENT,
    VETERINARY,
    ELECTRICAL_AND_MECHANICAL,
    OTHER
}