package com.civicsense.complaint.entity;

import com.civicsense.user.entity.User;
import com.civicsense.complaint.entity.cluster.ComplaintCluster;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "complaints")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Complaint {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /*
     * Citizen who submitted the complaint.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /*
     * Optional title.
     *
     * For now the citizen mainly provides a description.
     * A title can later be generated by the AI/classification layer.
     */
    @Column(length = 150)
    private String title;

    /*
     * Main complaint submitted by the citizen.
     *
     * Can be written in Hindi, English, Hinglish,
     * or another supported language.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    /*
     * Complaint category.
     *
     * This will be determined later by the classification/AI layer.
     */
    @Column(length = 50)
    private String category;

    /*
     * Location obtained from the user's device/browser
     * after location permission is granted.
     */
    @Column(nullable = false)
    private Double latitude;

    @Column(nullable = false)
    private Double longitude;

    /*
     * Optional address or additional location information
     * provided by the citizen.
     *
     * Example:
     * "Near ABC School, opposite the main gate"
     */
    @Column(length = 500)
    private String address;

    /*
     * Cluster to which this complaint belongs.
     *
     * A complaint can belong to one cluster,
     * while one cluster can contain multiple complaints.
     *
     * A complaint may initially have no cluster
     * until duplicate detection is completed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cluster_id")
    private ComplaintCluster cluster;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ComplaintStatus status = ComplaintStatus.SUBMITTED;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {

        LocalDateTime now = LocalDateTime.now();

        createdAt = now;
        updatedAt = now;
    }

    @PreUpdate
    protected void onUpdate() {

        updatedAt = LocalDateTime.now();
    }
}